EntityBundle\Entity\Video:
    properties:
        title:
            - NotBlank: ~
        url:
            - NotBlank: ~
            - Url: ~
            - Regex: '/https:\/\/www.youtube.com\/watch\?v=.........../'
        description:
            - NotBlank: ~