hamster_hub:
    resource: "@HamsterHubBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_registration_register:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"