EntityBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: EntityBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        birthdate:
            type: date
        imageName:
            type: string
            length: 255
            options:
                default: ''
        updatedAt:
            type: date
            options:
                default: '0000-00-00'
    lifecycleCallbacks: {  }
