EntityBundle\Entity\Video:
    type: entity
    table: null
    repositoryClass: EntityBundle\Repository\VideoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        url:
            type: string
            length: 255
        authorId:
            type: integer
            column: author_id
        uploadDate:
            type: datetime
            column: upload_date
    lifecycleCallbacks: {  }
