hamster_hub_homepage:
    path:     /
    defaults: { _controller: HamsterHubBundle:Default:index }

hamster_hub_dashboard:
    path:     /dashboard/{username}
    defaults: { _controller: HamsterHubBundle:Dashboard:index }

hamster_hub_channel:
    path:     /channel/{username}
    defaults: { _controller: HamsterHubBundle:Channel:index }

hamster_hub_watch:
      path:     /watch/{videoId}
      defaults: { _controller: HamsterHubBundle:Watch:index }

hamster_hub_upload:
      path:     /upload
      defaults: { _controller: HamsterHubBundle:Upload:index }
