hamster_hub_homepage:
    path:     /
    defaults: { _controller: HamsterHubBundle:Default:index }

hamster_hub_dashboard:
    path:     /dashboard
    defaults: { _controller: HamsterHubBundle:Dashboard:index }

hamster_hub_dashboard_remove:
    path:     /dashboard/{id}/remove
    defaults: { _controller: HamsterHubBundle:Dashboard:remove }

hamster_hub_dashboard_edit:
    path:     /dashboard/{id}/edit
    defaults: { _controller: HamsterHubBundle:Dashboard:edit }

hamster_hub_channel:
    path:     /channel/{username}
    defaults: { _controller: HamsterHubBundle:Channel:index }

hamster_hub_watch:
      path:     /watch/{videoId}
      defaults: { _controller: HamsterHubBundle:Watch:index }

hamster_hub_upload:
      path:     /upload
      defaults: { _controller: HamsterHubBundle:Upload:video }
